version: '3.8'

services:
  buyx_trade:
    build:
      context: ./buyx_trade
    ports:
      - '4002:4002'
    env_file:
      - ./buyx_trade/.env
    environment:
      - TZ=Asia/Shanghai
    networks:
      - app-network
    restart: unless-stopped

  nginx:
    image: nginx:1.25.3-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./html:/var/www/html  # 挂载 webroot
    ports:
      - "80:80"  # 仅映射80端口
    depends_on:
      - buyx_trade
    environment:
      - TZ=Asia/Shanghai
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge